/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.bean.ItensPedido;
import model.dao.ItensPedidoDAO;


public class testMenu extends javax.swing.JFrame {
   public ArrayList<Integer> arrayID = new ArrayList<>();
    String ano, mes;
    public testMenu() {
        initComponents();
        jCAno.addItem("2017");
        jCAno.addItem("2018");
        jCAno.addItem("2019");
        jCAno.addItem("2020");
        jCAno.addItem("2021");
        jCAno.addItem("2022");
        jCMes.addItem("11");
        jCMes.addItem("12");
            
        ano =  (String) jCAno.getSelectedItem();
   
    }
    
    public void readJTable(){
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        ItensPedidoDAO pedido = new ItensPedidoDAO();
        modelo.setNumRows(0);
        
       
        for (ItensPedido p : pedido.readAno(ano,mes)) {
                modelo.addRow(new Object[]{
                p.getPreco()
                
            });
                
        
    }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jCAno = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jBOkAno = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jCMes = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1440, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, 250, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Relatório de Vendas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 290, 40));

        getContentPane().add(jCAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 110, -1));

        jLabel2.setText("Ano:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        jBOkAno.setText("Ok");
        jBOkAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOkAnoActionPerformed(evt);
            }
        });
        getContentPane().add(jBOkAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, -1, -1));

        jLabel3.setText("Mês:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, -1, -1));

        getContentPane().add(jCMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBOkAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOkAnoActionPerformed
        ano = (String) jCAno.getSelectedItem();
        mes = (String) jCMes.getSelectedItem();
        
        ItensPedidoDAO pedido = new ItensPedidoDAO();
        pedido.readAno(ano,mes);
        readJTable();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jBOkAnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(testMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(testMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(testMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(testMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new testMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBOkAno;
    private javax.swing.JComboBox jCAno;
    private javax.swing.JComboBox jCMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
