/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.ItensPedido;
import model.bean.Pedido;
import model.bean.Produto;
import model.dao.ItensPedidoDAO;
import model.dao.ProdutoDAO;


public class Relatorios extends javax.swing.JFrame {
   public ArrayList<Integer> arrayID = new ArrayList<>();
    String ano, mes;
    public String data;
    public double counttotal;
    public double countmes;
    public double countdata;
    
    public String getAno() {
        return ano;
    }

    public void setAno(String ano) {
        this.ano = ano;
    }

    public String getMes() {
        return mes;
    }

    public void setMes(String mes) {
        this.mes = mes;
    }

    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }
    
    
    public Relatorios() {
        initComponents();
        
        jCMes.addItem("1");
        jCMes.addItem("2");
        jCMes.addItem("3");
        jCMes.addItem("4");
        jCMes.addItem("5");
        jCMes.addItem("6");
        jCMes.addItem("7");
        jCMes.addItem("8");
        jCMes.addItem("9");
        jCMes.addItem("10");
        jCMes.addItem("11");
        jCMes.addItem("12");
            
        
        setLocationRelativeTo(null);
    }
    
    
    public void readJTableVendas(){
        DefaultTableModel modelo = (DefaultTableModel) jTProdutos.getModel();
        ItensPedidoDAO pedido = new ItensPedidoDAO();
        counttotal = 0;
        for (ItensPedido p : pedido.readVendas()){
            counttotal += p.getPreco();
                modelo.addRow(new Object[]{
                p.getNomeCliente(),
                p.getNomePizza(),
                p.getTamanho(),
                p.getQuantidade(),  
                p.getPreco(),
                p.getMetodPag(),
                p.getData()
            });
                
        
    }
    }
    
    public void readJTableMes(){
        DefaultTableModel modelo = (DefaultTableModel) jTProdutos.getModel();
        ItensPedidoDAO pedido = new ItensPedidoDAO();
        //modelo.setNumRows(0);
        countmes = 0;
        for (ItensPedido p : pedido.readVendasMes(getMes())) {
            countmes += p.getPreco();
                modelo.addRow(new Object[]{
                p.getNomeCliente(),
                p.getNomePizza(),
                p.getTamanho(),
                p.getQuantidade(),  
                p.getPreco(),
                p.getMetodPag(),
                p.getData()
            });
                
        
    }
    }
    
    public void readJTableData(){
        DefaultTableModel modelo = (DefaultTableModel) jTProdutos.getModel();
        ItensPedidoDAO pedido = new ItensPedidoDAO();
        countdata = 0;
        for (ItensPedido p : pedido.readVendasDia(getData())) {
            countdata+= p.getPreco();
                modelo.addRow(new Object[]{
                p.getNomeCliente(),
                p.getNomePizza(),
                p.getTamanho(),
                p.getQuantidade(),  
                p.getPreco(),
                p.getMetodPag(),
                p.getData()
            });
                
        
    }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jBOkAno = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jCMes = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLTotal = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTProdutos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jCalendar = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatórios");
        setMaximumSize(new java.awt.Dimension(1140, 835));
        setMinimumSize(new java.awt.Dimension(1140, 835));
        setName("Relatórios"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1140, 835));
        setSize(new java.awt.Dimension(1140, 835));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Relatório de Vendas");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1140, 70);

        jBOkAno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBOkAno.setText("Ir");
        jBOkAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOkAnoActionPerformed(evt);
            }
        });
        getContentPane().add(jBOkAno);
        jBOkAno.setBounds(610, 90, 41, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mês:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 90, 40, 30);

        getContentPane().add(jCMes);
        jCMes.setBounds(80, 90, 100, 30);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total: R$");
        jLabel6.setPreferredSize(new java.awt.Dimension(80, 20));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(960, 650, 80, 20);

        jLTotal.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLTotal.setForeground(new java.awt.Color(0, 204, 51));
        jLTotal.setText("00,00");
        getContentPane().add(jLTotal);
        jLTotal.setBounds(1040, 650, 100, 20);

        jTProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome do Cliente", "Nome do Produto", "Tamanho", "Quantidade", "Preço", "Pagamento", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTProdutosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTProdutos);
        if (jTProdutos.getColumnModel().getColumnCount() > 0) {
            jTProdutos.getColumnModel().getColumn(0).setPreferredWidth(230);
            jTProdutos.getColumnModel().getColumn(1).setPreferredWidth(300);
        }

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(40, 130, 1060, 520);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Relatório de todas as vendas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(890, 80, 210, 40);

        jCalendar.setOpaque(false);
        getContentPane().add(jCalendar);
        jCalendar.setBounds(450, 90, 160, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Selecionar data:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(320, 90, 130, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setText("Vendas no mês");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(190, 90, 120, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/testeBack.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1440, 1092);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBOkAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOkAnoActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jTProdutos.getModel();
        modelo.setRowCount(0);
        java.util.Date pega = jCalendar.getDate();
        
        if(pega == null){
            JOptionPane.showMessageDialog(null, "Escolha uma data");
        }else{
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        setData(formato.format(pega));
        
        ItensPedidoDAO pedido = new ItensPedidoDAO();
        pedido.readVendasDia(getData());
        readJTableData();
        jLTotal.setText(String.valueOf(countdata));
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jBOkAnoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        DefaultTableModel modelo = (DefaultTableModel) jTProdutos.getModel();
        modelo.setRowCount(0);
        readJTableVendas(); 
        
        jLTotal.setText(String.valueOf(counttotal));
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
        DefaultTableModel modelo = (DefaultTableModel) jTProdutos.getModel();
        modelo.setRowCount(0);
        
        readJTableVendas();

        jLTotal.setText(String.valueOf(counttotal));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setMes((String) jCMes.getSelectedItem());
        
        DefaultTableModel modelo = (DefaultTableModel) jTProdutos.getModel();
        modelo.setRowCount(0);
        
        ItensPedidoDAO pedido = new ItensPedidoDAO();
        pedido.readVendasMes(getMes());
        
        readJTableMes();
        jLTotal.setText(String.valueOf(countmes));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTProdutosMouseClicked

    }//GEN-LAST:event_jTProdutosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Relatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Relatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Relatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Relatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Relatorios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBOkAno;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jCMes;
    private com.toedter.calendar.JDateChooser jCalendar;
    private javax.swing.JLabel jLTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTProdutos;
    // End of variables declaration//GEN-END:variables
}
